// // crypto-shim.js

// // Import individual crypto functionalities from Cloudflare's `node:crypto`
// import {
//   createHash,
//   createHmac,
//   getCiphers,
//   getHashes,
//   generateKey,
//   generateKeyPair,
//   generateKeyPairSync,
//   generateKeySync,
//   createSecretKey,
//   hkdf,
//   hkdfSync,
//   pbkdf2,
//   pbkdf2Sync,
//   randomBytes,
//   randomFill,
//   randomFillSync,
//   randomInt,
//   randomUUID,
//   subtle,
//   webcrypto,
//   secureHeapUsed,
//   setEngine,
//   timingSafeEqual,
//   getFips,
//   fips,
//   setFips,
//   createDiffieHellman,
//   createDiffieHellmanGroup,
//   getDiffieHellman,
//   checkPrime,
//   checkPrimeSync,
//   generatePrime,
//   generatePrimeSync,
// } from 'node:crypto';

// // Create an object with all the exported functionalities
// const cryptoExports = {
//   createHash,
//   createHmac,
//   getCiphers,
//   getHashes,
//   generateKey,
//   generateKeyPair,
//   generateKeyPairSync,
//   generateKeySync,
//   createSecretKey,
//   hkdf,
//   hkdfSync,
//   pbkdf2,
//   pbkdf2Sync,
//   randomBytes,
//   randomFill,
//   randomFillSync,
//   randomInt,
//   randomUUID,
//   subtle,
//   webcrypto,
//   secureHeapUsed,
//   setEngine,
//   timingSafeEqual,
//   getFips,
//   fips,
//   setFips,
//   createDiffieHellman,
//   createDiffieHellmanGroup,
//   getDiffieHellman,
//   checkPrime,
//   checkPrimeSync,
//   generatePrime,
//   generatePrimeSync,
// };

// // Check if `module` and `module.exports` exist (indicating a CommonJS environment)
// if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') {
//   // Export the functionalities using CommonJS syntax
//   module.exports = cryptoExports;
// } else {
//   // Export the functionalities using ES module syntax
//   export default cryptoExports;
// }

import {
  createHash,
  createHmac,
  getCiphers,
  getHashes,
  generateKey,
  generateKeyPair,
  generateKeyPairSync,
  generateKeySync,
  createSecretKey,
  hkdf,
  hkdfSync,
  pbkdf2,
  pbkdf2Sync,
  randomBytes,
  randomFill,
  randomFillSync,
  randomInt,
  randomUUID,
  subtle,
  webcrypto,
  secureHeapUsed,
  setEngine,
  timingSafeEqual,
  getFips,
  fips,
  setFips,
  createDiffieHellman,
  createDiffieHellmanGroup,
  getDiffieHellman,
  checkPrime,
  checkPrimeSync,
  generatePrime,
  generatePrimeSync,
} from 'node:crypto';

// Export them as a single module
export default {
  createHash,
  createHmac,
  getCiphers,
  getHashes,
  generateKey,
  generateKeyPair,
  generateKeyPairSync,
  generateKeySync,
  createSecretKey,
  hkdf,
  hkdfSync,
  pbkdf2,
  pbkdf2Sync,
  randomBytes,
  randomFill,
  randomFillSync,
  randomInt,
  randomUUID,
  subtle,
  webcrypto,
  secureHeapUsed,
  setEngine,
  timingSafeEqual,
  getFips,
  fips,
  setFips,
  createDiffieHellman,
  createDiffieHellmanGroup,
  getDiffieHellman,
  checkPrime,
  checkPrimeSync,
  generatePrime,
  generatePrimeSync,
};
